name: Test Report

on:
  workflow_run:
    workflows: ['My Demo']
    types:
      - completed

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        artifact: test-results
        name: Workflow Report
        path: '*.js'
        reporter: jest-junit